# SPDX-License-Identifier: GPL-2.0+

# Grab our configured image.  The source for this is found at:
# https://gitlab.denx.de/u-boot/gitlab-ci-runner
image: uboot2014-builder:1.0

variables:
  GIT_SSL_NO_VERIFY: "1"                     # Allow self-signed certificates (REQUIRED for gitlab.tpl)

# We run some tests in different order, to catch some failures quicker.
stages:
  - testsuites
  - test.py
  - tplatforms build
  - world build

# 129 is returned for warnings, so ignore them for now
build baikal-t:
  tags: [ 'all' ]
  stage: tplatforms build
  script:
    - ret=0;
     ./tools/buildman/buildman -o . -k tplatforms || ret=$?;
     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
       ./tools/buildman/buildman -o . -sde;
       exit $ret;
     fi;
  artifacts:
    name: "uboot_tplatforms"
    paths:
    - current/current
    expire_in: 1 month

# QA jobs for code analytics
# static code analysis with cppcheck (we can add --enable=all later)
cppcheck:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - cppcheck --force --quiet --inline-suppr .

# search for TODO within source tree
grep TODO/FIXME/HACK:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - grep -r TODO .
    - grep -r FIXME .
    # search for HACK within source tree and ignore HACKKIT board
    - grep -r HACK . | grep -v HACKKIT

# some statistics about the code base
sloccount:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - sloccount .

Check for configs without MAINTAINERS entry:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - if [ `./tools/genboardscfg.py -f 2>&1 | wc -l` -ne 0 ]; then exit 1; fi

# These platforms fail to build.

#build non-TP MIPS platforms:
#  tags: [ 'all' ]
#  stage: world build
#  script:
#    - ret=0;
#     ./tools/buildman/buildman -o /tmp -k mips -x tplatforms || ret=$?;
#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
#       ./tools/buildman/buildman -o /tmp -sde mips -x tplatforms;
#       exit $ret;
#     fi;
#
#build all 32bit ARM platforms:
#  tags: [ 'all' ]
#  stage: world build
#  script:
#    - ret=0;
#     ./tools/buildman/buildman -o /tmp -k arm -x aarch64 || ret=$?;
#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
#       ./tools/buildman/buildman -o /tmp -sde;
#       exit $ret;
#     fi;
#
#build all 64bit ARM platforms:
#  tags: [ 'all' ]
#  stage: world build
#  script:
#    - virtualenv /tmp/venv
#    - . /tmp/venv/bin/activate
#    - pip install pyelftools
#    - ret=0;
#     ./tools/buildman/buildman -o /tmp -k aarch64 || ret=$?;
#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
#       ./tools/buildman/buildman -o /tmp -sde;
#       exit $ret;
#     fi;
#
#build all PowerPC platforms:
#  tags: [ 'all' ]
#  stage: world build
#  script:
#    - ret=0;
#     ./tools/buildman/buildman -o /tmp -k powerpc || ret=$?;
#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
#       ./tools/buildman/buildman -o /tmp -sde;
#       exit $ret;
#     fi;
#
#build all other platforms:
#  tags: [ 'all' ]
#  stage: world build
#  script:
#    - ret=0;
#     ./tools/buildman/buildman -o /tmp -k -x arm,powerpc || ret=$?;
#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
#       ./tools/buildman/buildman -o /tmp -sde;
#       exit $ret;
#     fi;
