# SPDX-License-Identifier: GPL-2.0+

# Grab our configured image.  The source for this is found at:
# https://gitlab.denx.de/u-boot/gitlab-ci-runner
image: uboot2014-builder:1.0

variables:
  GIT_SSL_NO_VERIFY: "1"                     # Allow self-signed certificates (REQUIRED for gitlab.tpl)

# We run some tests in different order, to catch some failures quicker.
stages:
  - testsuites
  - test.py
  - tplatforms build
# NDZ disable for now, takes too long
#  - world build

build ours:
  tags: [ 'all' ]
  stage: tplatforms build
  script:
    - ret=0;
     ./tools/buildman/buildman -k tplatforms || ret=$?;
     # 129 is returned for warnings, so ignore them for now
     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
       ./tools/buildman/buildman -o .. -sde;
       exit $ret;
     fi;
  artifacts:
    name: "uboot_tplatforms"
    paths:
    - ../current/current/tplatforms_axt1-msbt2/u-boot.bin
    - ../current/current/tplatforms_axt1-sfbt1/u-boot.bin
    - ../current/current/tplatforms_bc3bt1-mrbt1/u-boot.bin
    - ../current/current/tplatforms_bn1bt1/u-boot.bin
    - ../current/current/tplatforms_cnc-msbt2/u-boot.bin
    - ../current/current/tplatforms_cnc-sfbt1/u-boot.bin
    - ../current/current/tplatforms_mitx/u-boot.bin
    - ../current/current/tplatforms_mitx_jumper/u-boot.bin
    - ../current/current/tplatforms_mrbt1/u-boot.bin
    - ../current/current/tplatforms_msbt2/u-boot.bin
    - ../current/current/tplatforms_rt1mb/u-boot.bin
    - ../current/current/tplatforms_sbc101/u-boot.bin
    - ../current/current/tplatforms_sfbt1/u-boot.bin
    - ../current/current/tplatforms_tc-msbt2/u-boot.bin
    - ../current/current/tplatforms_tc-sfbt1/u-boot.bin
    expire_in: 1 month

# QA jobs for code analytics
# static code analysis with cppcheck (we can add --enable=all later)
cppcheck:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - cppcheck --force --quiet --inline-suppr .

# search for TODO within source tree
grep TODO/FIXME/HACK:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - grep -r TODO .
    - grep -r FIXME .
    # search for HACK within source tree and ignore HACKKIT board
    - grep -r HACK . | grep -v HACKKIT

# some statistics about the code base
sloccount:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - sloccount .

Check for configs without MAINTAINERS entry:
  tags: [ 'all' ]
  stage: testsuites
  script:
    - if [ `./tools/genboardscfg.py -f 2>&1 | wc -l` -ne 0 ]; then exit 1; fi

